package uk.co.nikodem.DFJavaResourcesPlus;

import team.unnamed.creative.ResourcePack;
import team.unnamed.creative.base.Writable;
import team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriter;
import uk.co.nikodem.DFJavaResourcesPlus.AssetSearchers.ArmourSearcher;
import uk.co.nikodem.DFJavaResourcesPlus.AssetSearchers.BasicItemSearcher;
import uk.co.nikodem.DFJavaResourcesPlus.AssetSearchers.ToolSearcher;
import uk.co.nikodem.DFJavaResourcesPlus.Utils.Logger;

import java.io.File;
import java.util.List;

public class Main {
    public static String NAMESPACE = "dfjr";
    public static String MINECRAFT = "minecraft";

    public static String OUTPUT_FILENAME = "dfjavaresourcesplus.zip";

    public static int PACK_FORMAT = 64;
    public static String DESCRIPTION = "DFJavaResourcesPlus 1.21.7+ (Autogenerated)";

    public static Logger logger = new Logger();

    public static void main(String[] args) {
        logger.log("Main", "Starting resource pack compilation...");
        ResourcePack resourcePack = ResourcePack.resourcePack();

        List<AssetSearcher> assetSearchers = List.of(
                new ToolSearcher(),
                new BasicItemSearcher(),
                new ArmourSearcher()
        );

        for (AssetSearcher assetSearcher : assetSearchers) {
            logger.log("AssetSearchers", "Adding "+assetSearcher.getAssetTypeName()+" assets..");
            assetSearcher.run(resourcePack);
        }

        logger.log("Main", "Adding metadata..");
        resourcePack.packMeta(PACK_FORMAT, DESCRIPTION);
        resourcePack.icon(Writable.resource(ClassLoader.getSystemClassLoader(), "pack.png"));

        logger.log("Main", "Writing to zip..");
        MinecraftResourcePackWriter.minecraft().writeToZipFile(
                new File(OUTPUT_FILENAME),
                resourcePack
        );

        logger.log("Main", "Resource pack finished compiling!");
    }
}