package uk.co.nikodem.DFJavaResourcesPlus;

import team.unnamed.creative.ResourcePack;
import team.unnamed.creative.base.Writable;
import team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriter;
import uk.co.nikodem.DFJavaResourcesPlus.ItemBuilders.DFItemTexture;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.stream.Stream;

public class Main {
    public static String NAMESPACE = "dfjr";
    public static String MINECRAFT = "minecraft";

    public static String OUTPUT_FILENAME = "dfjavaresourcesplus.zip";

    public static int PACK_FORMAT = 64;
    public static String DESCRIPTION = "DFJavaResourcesPlus 1.21.7+ (Autogenerated)";

    public static void main(String[] args) {
        System.out.println("Starting resource pack creation..");
        ResourcePack resourcePack = ResourcePack.resourcePack();

        System.out.println("Adding item assets..");
        try (Stream<Path> paths = Files.walk(Paths.get("assets/items"))) {
            for (Path path : paths.toList()) {
                File img = path.toFile();
                if (!img.isFile()) continue;
                Writable writable = Writable.file(img);

                String[] split_filename = img.getName().split("\\.");
                String asset_name = split_filename[0];
                String file_extension = split_filename[1].toLowerCase();

                if (!file_extension.equals("png")) continue;

                System.out.println("Adding "+asset_name+"... Status: "+DFItemTexture.createItemTexture(resourcePack, asset_name, writable));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("Adding metadata..");
        resourcePack.packMeta(PACK_FORMAT, DESCRIPTION);
        resourcePack.icon(Writable.resource(ClassLoader.getSystemClassLoader(), "pack.png"));

        System.out.println("Writing to zip..");
        MinecraftResourcePackWriter.minecraft().writeToZipFile(
                new File(OUTPUT_FILENAME),
                resourcePack
        );

        System.out.println("Done!");
    }
}